server:
  port: 8093

spring:
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:sqlserver://${DATABASE_URL:localhost:1433};DatabaseName=${DATABASE_SCHEMA:SYNPULSE_TRANX_DB};trustServerCertificate=true
    username: ${DATABASE_USER:sa}
    password: ${DATABASE_PASSWORD:Demo9731}
  kafka:
    bootstrap-servers: ${CONTAINER_HOST:localhost}:9092
  consumer:
    deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
